imports:
    - { resource: base_config.yml }
    
overwatch_service:
    to_ping: ~
    to_resolve_to: ~
    to_respond_http: ~
    to_respond_with_mime_type: ~
    email_reporter:
        report_from: %mailer_from%
